#!/usr/bin/env python3
"""
Convert NCBI Assembly accessions to Biosample metadata table.
Requires: biopython
Install with: pip install biopython

Generated by Claude initially
"""

import sys
import time
import csv
from collections import defaultdict
from Bio import Entrez

parser = argparse.ArgumentParser(description='Extract BioSample metadata from NCBI Entrez.')

parser.add_argument('-o', '--output', metavar=("out"), required=False,
                    help='Output table presenting lookup results' +
                    ' if file already exists will update the file' +
                    ' or append with new samples')

parser.add_argument('-i', '--input', metavar=("in"), required=False,
                    help='Input file of sample names')


parser.add_argument('-e', '--email', required=True,
                    help='Input your email address for Entrez queries')

parser.add_argument('-u', '--update', required=False, action='store_true',
                    help='Input sample names as list')

parser.add_argument('--debug', required=False, action='store_true',
                    help='Debug this running')

args = parser.parse_args()

# Set your email for NCBI (required by their API)
Entrez.email = args.email 

separator = "\t"
query = set()
header_set = set()
assemblies = {}
if args.output:
    if re.search(r'\.(csv|CSV)$', args.output):
        separator = ","
    if os.path.exists(args.output):
        with open(args.output, "rt") as fh:
            csvin = csv.reader(fh, delimiter=separator)
            header = next(csvin)
            for h in header[1:]:
                header_set.add(h)
            for row in csvin:
                sampleid = row[0]
                assemblies[sampleid] = {}
                # skip column 1 since it is the ID column
                for i in range(1, len(header)):
                    assemblies[sampleid][header[i]] = row[i]

if args.assemblies:
    for r in args.assemblies:
        if args.update or not (r in assemblies):
            query.add(r)
else:
    with open(args.input, 'rt') if args.input else sys.stdin as fh:
        for line in fh:
            line = line.strip()
            if args.update or not (line in assemblies):
                print("adding line {}".format(line))
                query.add(line)

        
def fetch_assembly_info(assembly_acc):
    """Fetch assembly information including biosample accession."""
    try:
        handle = Entrez.esearch(db="assembly", term=assembly_acc, retmax=1)
        record = Entrez.read(handle)
        handle.close()
        
        if not record['IdList']:
            print(f"Warning: No assembly found for {assembly_acc}", file=sys.stderr)
            return None
        
        assembly_id = record['IdList'][0]
        
        # Fetch assembly summary
        handle = Entrez.esummary(db="assembly", id=assembly_id)
        summary = Entrez.read(handle, validate=False)
        handle.close()
        
        if 'DocumentSummarySet' in summary and 'DocumentSummary' in summary['DocumentSummarySet']:
            doc_summary = summary['DocumentSummarySet']['DocumentSummary'][0]
            biosample_acc = doc_summary.get('BioSampleAccn', '')
            return biosample_acc
        
        return None
    except Exception as e:
        print(f"Error fetching assembly {assembly_acc}: {e}", file=sys.stderr)
        return None

def fetch_biosample_metadata(biosample_acc):
    """Fetch all metadata fields from a biosample."""
    try:
        handle = Entrez.esearch(db="biosample", term=biosample_acc, retmax=1)
        record = Entrez.read(handle)
        handle.close()
        
        if not record['IdList']:
            print(f"Warning: No biosample found for {biosample_acc}", file=sys.stderr)
            return {}
        
        biosample_id = record['IdList'][0]
        
        # Fetch biosample record
        handle = Entrez.efetch(db="biosample", id=biosample_id, rettype="xml")
        data = handle.read()
        handle.close()
        
        # Parse XML
        from xml.etree import ElementTree as ET
        root = ET.fromstring(data)
        
        metadata = {}
        
        # Extract attributes
        for attr in root.findall('.//Attribute'):
            attr_name = attr.get('attribute_name', 'unknown')
            attr_value = attr.text if attr.text else ''
            metadata[attr_name] = attr_value
        
        return metadata
    except Exception as e:
        print(f"Error fetching biosample {biosample_acc}: {e}", file=sys.stderr)
        return {}

def main():
    if len(sys.argv) != 2:
        print("Usage: python script.py <input_file>")
        print("Input file should contain one assembly accession per line")
        sys.exit(1)
    
    input_file = sys.argv[1]
    
    # Read assembly accessions
    with open(input_file, 'r') as f:
        assembly_accs = [line.strip() for line in f if line.strip()]
    
    print(f"Processing {len(assembly_accs)} assembly accessions...", file=sys.stderr)
    
    # Collect all data
    all_data = []
    all_fields = set(['assembly_accession', 'biosample_accession'])
    
    for i, assembly_acc in enumerate(assembly_accs, 1):
        print(f"Processing {i}/{len(assembly_accs)}: {assembly_acc}", file=sys.stderr)
        
        # Get biosample accession
        biosample_acc = fetch_assembly_info(assembly_acc)
        
        if not biosample_acc:
            # Still add row with assembly accession
            all_data.append({
                'assembly_accession': assembly_acc,
                'biosample_accession': ''
            })
            continue
        
        # Get biosample metadata
        time.sleep(0.34)  # NCBI rate limit: 3 requests per second
        metadata = fetch_biosample_metadata(biosample_acc)
        
        # Combine data
        row_data = {
            'assembly_accession': assembly_acc,
            'biosample_accession': biosample_acc,
            **metadata
        }
        
        all_data.append(row_data)
        all_fields.update(metadata.keys())
        
        time.sleep(0.34)  # NCBI rate limit
    
    # Write output as TSV
    output_file = 'assembly_biosample_metadata.tsv'
    all_fields = sorted(all_fields)
    
    with open(output_file, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=all_fields, delimiter='\t', extrasaction='ignore')
        writer.writeheader()
        
        for row in all_data:
            writer.writerow(row)
    
    print(f"\nOutput written to: {output_file}", file=sys.stderr)
    print(f"Total records: {len(all_data)}", file=sys.stderr)
    print(f"Total metadata fields: {len(all_fields)}", file=sys.stderr)

if __name__ == "__main__":
    main()
